name: Load Value

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  load-value: 
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Restore cached value
        uses: actions/cache@v4
        with:
          path: value.txt
          key: shared-value-key

      - name: Read value
        run: cat value.txt